CREATE TABLE public.athletes (
CREATE TABLE public.event_boxscores_batting (
CREATE TABLE public.event_boxscores_pitching (
CREATE TABLE public.event_competitors (
CREATE TABLE public.event_odds (
CREATE TABLE public.event_plays (
CREATE TABLE public.event_win_probability (
CREATE TABLE public.events (
CREATE TABLE public.groups (
CREATE TABLE public.player_props (
CREATE TABLE public.positions (
CREATE TABLE public.season_rosters (
CREATE TABLE public.season_teams (
CREATE TABLE public.season_types (
CREATE TABLE public.seasons (
